### ISSUE TITLE
Add a (configurable) on-focused color for folders in the sidebar.

### ISSUE THREAD

**Issue by jfcherng** [dubeg/theme-dc#1]
Sublime allows us to change the focus to the sidebar by using Ctrl+0 (Windows).
And then we can navigate the sidebar by ↑↓←→.

In most of themes, take Cobalt2 for an example, it highlights the background of the on-focused folder.
![2015-02-02_03-32-48](https://cloud.githubusercontent.com/assets/6594915/5993468/6a158c2c-aa8c-11e4-91fa-4dd0cca75e71.png)

But I just found that in theme-dc, there is nothing different.
I can't even tell where I am.

Thanks for your great work.
Theme-dc has a beautiful and noticeable coloring.

**Comment by dubeg** [comment]
I didn't know about that feature! I updated the theme, with v1.2.5, you'll be able to highlight the active row with the setting "dc_highlight_active_sidebar_row" set to true.

Thanks.
